const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#F5C518",
    background: "#f5f5f5",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#F5C518",
    primaryForeground: "#1a1a1a",
    secondary: "#FFF8E1",
    secondaryForeground: "#8B6914",
    muted: "#f0f0f0",
    mutedForeground: "#8c8c8c",
    accent: "#FFF8E1",
    accentForeground: "#8B6914",
    destructive: "#E53935",
    destructiveForeground: "#ffffff",
    border: "#ebebeb",
    input: "#ebebeb",
    warning: "#FF9800",
    warningForeground: "#ffffff",
    success: "#43A047",
    successForeground: "#ffffff",
    info: "#1E88E5",
    infoForeground: "#ffffff",
    offline: "#E53935",
    syncing: "#FF9800",
    dark: "#1a1a1a",
    darkSecondary: "#2a2a2a",
    darkMuted: "#3a3a3a",
  },
  radius: 14,
};

export default colors;
