import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import branchesRouter from "./branches";
import stationsRouter from "./stations";
import clientsRouter from "./clients";
import assetsRouter from "./assets";
import rentalsRouter from "./rentals";
import blacklistRouter from "./blacklist";
import publicRouter from "./public";
import inquiriesRouter from "./inquiries";
import b2bRequestsRouter from "./b2b-requests";
import notificationsRouter from "./notifications";
import companySettingsRouter from "./company-settings";
import devicesRouter from "./devices";
import assetDevicesRouter from "./asset-devices";
import telemetryRouter from "./telemetry";
import batteriesRouter from "./batteries";
import geofencesRouter from "./geofences";
import commandsRouter from "./commands";
import reportsRouter from "./reports";
import providerApiKeysRouter from "./provider-api-keys";
import scanRouter from "./scan";
import pushTokensRouter from "./push-tokens";
import attachmentsRouter from "./attachments";
import storageRouter from "./storage";
import platformAuditRouter from "./platform-audit";
import platformSupportRouter from "./platform-support";
import platformBillingRouter from "./platform-billing";
import platformBlacklistRouter from "./platform-blacklist";
import platformWhiteLabelRouter from "./platform-white-label";
import platformDiagnosticsRouter from "./platform-diagnostics";
import platformAnalyticsRouter from "./platform-analytics";
import auditLogsRouter from "./audit-logs";

const router: IRouter = Router();

router.use(publicRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(branchesRouter);
router.use(stationsRouter);
router.use(clientsRouter);
router.use(assetsRouter);
router.use(rentalsRouter);
router.use(blacklistRouter);
router.use(inquiriesRouter);
router.use(b2bRequestsRouter);
router.use(notificationsRouter);
router.use(companySettingsRouter);
router.use(devicesRouter);
router.use(assetDevicesRouter);
router.use(telemetryRouter);
router.use(batteriesRouter);
router.use(geofencesRouter);
router.use(commandsRouter);
router.use(reportsRouter);
router.use(providerApiKeysRouter);
router.use(scanRouter);
router.use(pushTokensRouter);
router.use(attachmentsRouter);
router.use(storageRouter);
router.use(platformAuditRouter);
router.use(platformSupportRouter);
router.use(platformBillingRouter);
router.use(platformBlacklistRouter);
router.use(platformWhiteLabelRouter);
router.use(platformDiagnosticsRouter);
router.use(platformAnalyticsRouter);
router.use(auditLogsRouter);

export default router;
